describe('Login Tela', () => {
    it('Login teste Realizado Correto', () => {
      cy.viewport(1920, 1080) 
      cy.visit('/CadastroAssociado.php')
      cy.get(".bx").click()
      cy.get("#nome.input").type("Elielzin")
      cy.get("#nome.input").should("be.visible")
      cy.get("#data_nascimento.input").type("2008-07-10")
      cy.get("#data_nascimento.input").should("be.visible")
      cy.get("#cpf.input").type("485.565.455-75")
      cy.get("#cpf.input").should("be.visible")
      cy.get("#email.input").type("teste@teste")
      cy.get("#email.input").should("be.visible")
      cy.get("#telefone.input").type("679925-6895")
      cy.get("#telefone.input").should("be.visible")
      cy.get(".caixa_texto").type("KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK")
      cy.get(".caixa_texto").should("be.visible")
      cy.get("#termos").click()
      cy.get(".botaoConfirmar").click()
      cy.get(".btn").click()
    })
    it('Login teste SemTudo', () => {
      cy.viewport(1920, 1080) 
      cy.visit('/CadastroAssociado.php')
      cy.get(".bx").click()
      cy.get("#nome.input").type(" ")
      cy.get("#nome.input").should("be.visible")
      cy.get("#cpf.input").type(" ")
      cy.get("#cpf.input").should("be.visible")
      cy.get("#email.input").type(" ")
      cy.get("#email.input").should("be.visible")
      cy.get("#telefone.input").type(" ")
      cy.get("#telefone.input").should("be.visible")
      cy.get(".caixa_texto").type(" ")
      cy.get(".caixa_texto").should("be.visible")
      cy.get("#termos").click()
      cy.get(".botaoConfirmar").click()
      cy.get(".btn").click()
    })
    it('Login teste SemNome', () => {
      cy.viewport(1920, 1080) 
      cy.visit('/CadastroAssociado.php')
      cy.get(".bx").click()
      cy.get("#nome.input").type(" ")
      cy.get("#nome.input").should("be.visible")
      cy.get("#data_nascimento.input").type("2008-07-10")
      cy.get("#data_nascimento.input").should("be.visible")
      cy.get("#cpf.input").type("485.565.455-75")
      cy.get("#cpf.input").should("be.visible")
      cy.get("#email.input").type("teste@teste")
      cy.get("#email.input").should("be.visible")
      cy.get("#telefone.input").type("679925-6895")
      cy.get("#telefone.input").should("be.visible")
      cy.get(".caixa_texto").type("KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK")
      cy.get(".caixa_texto").should("be.visible")
      cy.get("#termos").click()
      cy.get(".botaoConfirmar").click()
      cy.get(".btn").click()
    })
    it('Login teste SemEmail', () => {
      cy.viewport(1920, 1080) 
      cy.visit('/CadastroAssociado.php')
      cy.get(".bx").click()
      cy.get("#nome.input").type("Elielzin")
      cy.get("#nome.input").should("be.visible")
      cy.get("#data_nascimento.input").type("2008-07-10")
      cy.get("#data_nascimento.input").should("be.visible")
      cy.get("#cpf.input").type("485.565.455-75")
      cy.get("#cpf.input").should("be.visible")
      cy.get("#email.input").type(" ")
      cy.get("#email.input").should("be.visible")
      cy.get("#telefone.input").type("679925-6895")
      cy.get("#telefone.input").should("be.visible")
      cy.get(".caixa_texto").type("KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK")
      cy.get(".caixa_texto").should("be.visible")
      cy.get("#termos").click()
      cy.get(".botaoConfirmar").click()
      cy.get(".btn").click()
    })
    it('Login teste SemCpf', () => {
      cy.viewport(1920, 1080) 
      cy.visit('/CadastroAssociado.php')
      cy.get(".bx").click()
      cy.get("#nome.input").type("Elielzin")
      cy.get("#nome.input").should("be.visible")
      cy.get("#data_nascimento.input").type("2008-07-10")
      cy.get("#data_nascimento.input").should("be.visible")
      cy.get("#cpf.input").type(" ")
      cy.get("#cpf.input").should("be.visible")
      cy.get("#email.input").type("teste@teste")
      cy.get("#email.input").should("be.visible")
      cy.get("#telefone.input").type("679925-6895")
      cy.get("#telefone.input").should("be.visible")
      cy.get(".caixa_texto").type("KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK")
      cy.get(".caixa_texto").should("be.visible")
      cy.get("#termos").click()
      cy.get(".botaoConfirmar").click()
      cy.get(".btn").click()
    })
    it('Login teste SemNumero', () => {
      cy.viewport(1920, 1080) 
      cy.visit('/CadastroAssociado.php')
      cy.get(".bx").click()
      cy.get("#nome.input").type("Elielzin")
      cy.get("#nome.input").should("be.visible")
      cy.get("#data_nascimento.input").type("2008-07-10")
      cy.get("#data_nascimento.input").should("be.visible")
      cy.get("#cpf.input").type("485.565.455-75")
      cy.get("#cpf.input").should("be.visible")
      cy.get("#email.input").type("teste@teste")
      cy.get("#email.input").should("be.visible")
      cy.get("#telefone.input").type(" ")
      cy.get("#telefone.input").should("be.visible")
      cy.get(".caixa_texto").type("KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK")
      cy.get(".caixa_texto").should("be.visible")
      cy.get("#termos").click()
      cy.get(".botaoConfirmar").click()
      cy.get(".btn").click()
    })
    it('Login teste SemTexto', () => {
      cy.viewport(1920, 1080) 
      cy.visit('/CadastroAssociado.php')
      cy.get(".bx").click()
      cy.get("#nome.input").type("Elielzin")
      cy.get("#nome.input").should("be.visible")
      cy.get("#data_nascimento.input").type("2008-07-10")
      cy.get("#data_nascimento.input").should("be.visible")
      cy.get("#cpf.input").type("485.565.455-75")
      cy.get("#cpf.input").should("be.visible")
      cy.get("#email.input").type("teste@teste")
      cy.get("#email.input").should("be.visible")
      cy.get("#telefone.input").type("679925-6895")
      cy.get("#telefone.input").should("be.visible")
      cy.get(".caixa_texto").type(" ")
      cy.get(".caixa_texto").should("be.visible")
      cy.get("#termos").click()
      cy.get(".botaoConfirmar").click()
      cy.get(".btn").click()
    })
})