describe('Login Tela', () => {
    it('Login teste Realizado Tudo Correto', () => {
      cy.viewport(1920, 1080) 
      cy.visit('/ProdutosAssociado.php')
      cy.get(":nth-child(1) > .nav-link").click()
      cy.get(":nth-child(2) > .nav-link").click()
      cy.get(":nth-child(1) > .nav-link").click()
      cy.get(":nth-child(3) > .nav-link").click()
      cy.get(":nth-child(1) > .nav-link").click()
      cy.get(":nth-child(4) > .nav-link").click()
      cy.get(":nth-child(1) > .nav-link").click()
      cy.get(":nth-child(5) > .nav-link").click()
      cy.get(":nth-child(2) > .nav-link").click()
      cy.get("#inputPesquisar").type("SLAPOHAAAAAAA")
      cy.get("#botaoAssociados").click()
      cy.get(":nth-child(1) > :nth-child(1) > [name='nome']").type("KKKKKKKKKKKKKKKKKKKKKKKKK")
      cy.get(":nth-child(1) > :nth-child(2) > [name='marca']").type("KKKKKKKKKKKKKKKKKKKKKKKKK")
      // cy.get(':nth-child(1) > :nth-child(3) > [name="subCategoria"]').click()
      cy.get(".campos-cadastrar > .divisao-esquerda > .campos-esquerda > :nth-child(1) > [name='qtdEstoque']").type("1000")
      cy.get(".campos-cadastrar > .divisao-esquerda > .campos-esquerda > :nth-child(2) > [name='preco']").type("999")
      cy.get('.campos-cadastrar > .divisao-esquerda > .campos-esquerda > :nth-child(3) > [name="precoPromocional"]').type("500")
      cy.get('.campos-cadastrar > .divisao-esquerda > .campos-esquerda > .chkPromocao > [name="fgPromocao"]').click()
      cy.get(':nth-child(2) > [name="breveDescricao"]').type("KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK")
      cy.get('.campos-cadastrar > .container-campos-large > .campo > [name="caracteristicasCompleta"]').type("Breve Descrição")
      cy.get(".header-cadastrar > .btn-fechar > .img-fechar").click()
      cy.get('#button_sair').click()
      cy.get('.btn-link').click()
    })
})