describe('Tela Principal', () => {
    it('Cadastro teste Realizado Correto', () => {
      cy.viewport(1920, 1080) 
      cy.visit('/paginaPrincipal.php')
      cy.wait(1000)
      cy.scrollTo(0, 9999, { duration: 1000 })
      cy.wait(1000)
      cy.get('.VoltarInicio').click()
      cy.wait(1000)
      cy.get('#headerCarousel > .esquerdo > #menu-toggle').click()
      cy.wait(1000)
      cy.get('#overlay').click()
      cy.get('#headerCarousel > .direito > .botoes > .lupaHeader').click()
      cy.wait(1000)
      cy.get('#headerCarousel > .direito > .botoes > .lupaHeader').click()
      cy.wait(1000)
      cy.get('#headerCarousel > .direito > .botoes > [href="/projeto-integrador-et.com/app/views/usuario/listaDeDesejos.php"] > img').click()
      cy.wait(1000)
      cy.go('back');
      cy.wait(1000)
      cy.get('#BolasContainer > :nth-child(1)').click()
      cy.wait(1000)
      cy.get('img[src*="/projeto-integrador-et.com/public/imagens/produto/hinode.png"]').click()
      cy.wait(1000)
      cy.get('img[src*="/projeto-integrador-et.com/public/imagens/produto/hinode.png"]').click()
      cy.wait(1000)
      cy.get('#BolasContainer > :nth-child(2)').click()
      cy.wait(1000)
      cy.get('img[src*="/projeto-integrador-et.com/public/imagens/produto/bocarosa.png"]').click()
      cy.wait(1000)
      cy.get('img[src*="/projeto-integrador-et.com/public/imagens/produto/bocarosa.png"]').click()
      cy.wait(1000)
      cy.get('#BolasContainer > :nth-child(3)').click()
      cy.wait(1000)
      cy.get('img[src*="/projeto-integrador-et.com/public/imagens/produto/leite.png"]').click()
      cy.wait(1000)
      cy.get('img[src*="/projeto-integrador-et.com/public/imagens/produto/leite.png"]').click()
      cy.wait(1000)
      cy.get('#BolasContainer > :nth-child(2)').click()
      cy.wait(1000)
      cy.get('img[src*="/projeto-integrador-et.com/public/imagens/produto/bocarosa.png"]').click()
      cy.wait(1000)
      cy.get('img[src*="/projeto-integrador-et.com/public/imagens/produto/bocarosa.png"]').click()
      cy.wait(1000)
      cy.get('#BolasContainer > :nth-child(1)').click()
      cy.wait(1000)
      cy.get('img[src*="/projeto-integrador-et.com/public/imagens/produto/hinode.png"]').click()
      cy.wait(1000)
      cy.get('img[src*="/projeto-integrador-et.com/public/imagens/produto/hinode.png"]').click()
      cy.wait(1000)
      cy.get('.VoltarInicio').click()
    })
})
